INSERT INTO "User" ("User".email, "User".first_name, "User".last_name, "User".pin)
VALUES ('Josborne37@gatech.edu', 'Austin', 'Osborne', '1234')
INSERT INTO "User" ("User".email, "User".first_name, "User".last_name, "User".pin)
VALUES ('xiaoxiaoyu@gatech.edu', 'Michelle', 'Yu', '1234')
INSERT INTO "User" ("User".email, "User".first_name, "User".last_name, "User".pin)
VALUES ('jmoen6@gatech.edu', 'Jon', 'Moen', '1234')
INSERT INTO "User" ("User".email, "User".first_name, "User".last_name, "User".pin)
VALUES ('jiaqi.gu@gatech.edu', 'Jiaqi', 'Gu', '1234')
INSERT INTO "User" ("User".email, "User".first_name, "User".last_name, "User".pin)
VALUES ('leo.mark@pe.gatech.edu', 'Leo', 'Mark', '1234')
INSERT INTO "User" ("User".email, "User".first_name, "User".last_name, "User".pin)
VALUES ('peter.graening@gatech.edu', 'Peter', 'Graening', '1234')
INSERT INTO "User" ("User".email, "User".first_name, "User".last_name, "User".pin)
VALUES ('tjohnson306@gatech.edu', 'Will', 'Johnson', '1234')